name: webview_flutter_example
description: Demonstrates how to use the webview_flutter plugin.

version: 1.0.3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
    - assets/css/jianshu.css
    - assets/google.png
    - assets/baidu.png
